---
- name: Pythonパッケージをインストール
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-venv

- name: 仮想環境を作成
  command: python3 -m venv /opt/app/venv
  args:
    creates: /opt/app/venv/bin/activate

- name: requirements.txtを作成
  copy:
    content: |
      flask==2.3.3
      sqlite3
      requests==2.31.0
    dest: /opt/app/requirements.txt
    mode: '0644'

- name: 依存関係をインストール
  pip:
    requirements: /opt/app/requirements.txt
    virtualenv: /opt/app/venv

- name: アプリケーションファイルを作成
  copy:
    content: |
      from flask import Flask, jsonify
      import sqlite3
      import os
      
      app = Flask(__name__)
      
      def get_db_connection():
          conn = sqlite3.connect('/var/lib/app/app.db')
          conn.row_factory = sqlite3.Row
          return conn
      
      @app.route('/')
      def index():
          return jsonify({
              'message': 'Ansibleでデプロイされたアプリケーション',
              'status': 'running'
          })
      
      @app.route('/users')
      def get_users():
          conn = get_db_connection()
          users = conn.execute('SELECT * FROM users').fetchall()
          conn.close()
          return jsonify([dict(user) for user in users])
      
      @app.route('/health')
      def health():
          return jsonify({'status': 'healthy'})
      
      if __name__ == '__main__':
          app.run(host='0.0.0.0', port=5000)
    dest: /opt/app/app.py
    mode: '0644'

- name: systemdサービスファイルを作成
  copy:
    content: |
      [Unit]
      Description=Ansible Training App
      After=network.target
      
      [Service]
      Type=simple
      User={{ ansible_user }}
      WorkingDirectory=/opt/app
      Environment=PATH=/opt/app/venv/bin
      ExecStart=/opt/app/venv/bin/python app.py
      Restart=always
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/ansible-app.service
    mode: '0644'

- name: systemdをリロード
  systemd:
    daemon_reload: yes

- name: アプリケーションサービスを開始
  systemd:
    name: ansible-app
    state: started
    enabled: yes 